# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #!/bin/bash
    for ((i=1; i<=100000; i++))
    do
        echo "this is a test message,  with index of $i"
    done
  displayName: 'echo'
